### ISSUE TITLE
Sensor layout not accurate

### ISSUE THREAD

**Issue by dogtopus** [jmontineri/OpeNITHM#6]
The real chunithm sensor has 16x2 layout which this project is lacking. AFAIK some WE charts (could be in other difficulty as well, not entirely sure) in vanilla chunithm rely on this to work so these will be unplayable on current OpeNITHM.

**Comment by veroxzik** [comment]
You can still use the 16x1 layout by reading relative capacitance and having two thresholds. Having 1 finger on the pad vs 2 fingers results in a significant change in the values read by the sensor.
FWIW, in my fork of OpeNITHM, I've switched to a Teensy LC to leverage the built in capacitive touch hardware (a quick peek through your github indicates you've worked quite a bit with it as well!) and I haven't found any problem at all differentiating between 1 and 2 fingers on a single key.
With that in mind, I am also not good enough to play WE charts! My testing has been limited to around 11s at this point.

**Comment by dogtopus** [comment]
A side note: As for capacitive sensing, I would recommend a CapSense-enabled PSoC since almost all its GPIO pins can be configured for capacitive sensing. It also has configurable sensitivity settings and can sense through gloves while maintain reasonably high frame rate after a bit of tweaking. It's perfect for high sensor count single chip solutions and the dev board is dirt cheap ($10 for cy8ckit-043 which offers just enough pins for a full chunithm/diva slider)

**Comment by dogtopus** [comment]
No longer an issue since v2.1.

From README:

> As of 2020-07-17, the recommended board version is v2.1, which features inputs for 32 sensors. This best replicates the feeling of the arcade. Previous versions used 16 sensors. If you still wish to make a 16 key version, you can order the v2.1 but only populate two of the multiplexers. This is not really recommended.

Close this now.
